### PR TITLE
Feature/NavBar

### PR DESCRIPTION
**Pull request by yasmws**
Created NavBar - with the logo img, a button and the name of the other pages. The code is in inside the 'components' folder.

### CODE REVIEW

**Review by liviabion — CHANGES_REQUESTED** [review]
On client/src/pages/index 
How it is:
import { Home } from './Home';
How it's supost to be:
import { Home } from './home';

**Review by liviabion — DISMISSED** [review]
Congrats :)))
Well Done!!!!!!!!!!!!!!

**Review by liviabion — APPROVED** [review]
Conflits solved

**Review by DamattaGa — APPROVED** [review]
Ok

**Pull request merged**
